### ISSUE TITLE
Integrate an MQTT client

### ISSUE THREAD

**Issue by raomin** [plapointe6/HAMqttDevice#5]
Your library is a good start. But why do you stop at the configuration only?
You could pass an MQTT client to the class and handle the messages and events too! eg. setAttribute(name,value), send(), etc.
Are you planning on this? 

-Raomin

**Comment by plapointe6** [comment]
Hello, I planned to do something similar initially.
However, there was alway a special case where I needed more flexibility and control. Because of that, I ended up making this a small usefull tool instead of a full library. I like it like this and I don't plan to implement these automations.

In fact, if you want a library that do almost everything by it's own, you could try ESPHome.

**Comment by fabiosoft** [comment]
Works good with `EspMQTTClient` library
